student_name = input("Enter student's name: ")
age = input("Enter student's age: ")
class_number = input("Enter student's class(1-12):")
physics = float(input("Physics marks: "))
chemistry = float(input("Chemistry marks: "))
biology = float(input("Biology marks: "))
ss = float(input("SS marks: "))
english = float(input("English marks: "))
hindi = float(input("Hindi marks: "))
print("Welcome", student_name,'\n',"You scored", round(((physics+chemistry+biology+ss+english+hindi)/6),2), "%")